from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNIT = ROOT / "deploy" / "systemd" / "cloakbrowser-acpx-worker.service.template"
REQUIREMENTS = ROOT / "scripts" / "requirements-acpx-worker.txt"
REQUIREMENTS_IN = ROOT / "scripts" / "requirements-acpx-worker.in"
REQUIREMENTS_LOCK = ROOT / "scripts" / "requirements-acpx-worker.linux-x86_64.py312.txt"
ACPX_PACKAGE = ROOT / "deploy" / "acpx-runtime" / "package.json"
ACPX_LOCK = ROOT / "deploy" / "acpx-runtime" / "package-lock.json"


def test_acpx_worker_unit_is_private_restartable_and_explicitly_configured():
    text = UNIT.read_text(encoding="utf-8")
    assert "UMask=0077" in text
    assert "Restart=on-failure" in text
    assert "-m scripts.acpx_worker" in text
    for placeholder in (
        "@WORKING_DIRECTORY@",
        "@VENV_PYTHON@",
        "@MANAGER_URL@",
        "@WORKER_ID@",
        "@TOKEN_FILE@",
        "@ACPX_EXECUTABLE@",
        "@PERMISSION_POLICY@",
        "@MCP_CONFIG@",
        "@CAPABILITY_DIR@",
    ):
        assert placeholder in text
    assert "--token " not in text
    assert "--token-file @TOKEN_FILE@" in text
    assert "Environment=CBM_MCP_PYTHON=@VENV_PYTHON@" in text


def test_acpx_worker_legacy_requirements_are_marked_non_production():
    text = REQUIREMENTS.read_text(encoding="utf-8")
    assert "LEGACY NON-PRODUCTION" in text
    assert "uv pip sync" not in text


def test_acpx_worker_runtime_lock_files_are_production_contract():
    lines = {
        line.strip()
        for line in REQUIREMENTS_IN.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }
    assert lines == {"aiohttp>=3.12,<4", "mcp==1.28.1", "playwright==1.61.0"}
    lock = REQUIREMENTS_LOCK.read_text(encoding="utf-8")
    assert lock.startswith(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile scripts/requirements-acpx-worker.in --output-file "
        "scripts/requirements-acpx-worker.linux-x86_64.py312.txt --python-version 3.12 "
        "--python-platform x86_64-manylinux2014 --generate-hashes --exclude-newer 2026-07-27T00:00:00Z\n"
    )
    assert "aiohttp==3.14.3" in lock
    assert "mcp==1.28.1" in lock
    assert "playwright==1.61.0" in lock
    assert "httpx==0.28.1" in lock
    assert "--hash=sha256:" in lock

    package = ACPX_PACKAGE.read_text(encoding="utf-8")
    assert '"private": true' in package
    assert '"acpx": "0.12.1"' in package
    assert '"@agentclientprotocol/sdk": "1.2.1"' in package
    assert '"node": ">=22.13.0"' in package

    lock_json = ACPX_LOCK.read_text(encoding="utf-8")
    assert '"lockfileVersion": 3' in lock_json
    assert "sha512-MoV932yPJUcjkX2L9u5TeFncvrxVD+jNTd3ES/tslaiT78S/7CwtgintmX9bonPbSgOB9vinvN+1OCHTQq4HJg==" in lock_json
    assert "sha512-jwYUdOQR7tc+Zfch53VL4JJyUNK/46q03uUTYb+PjECsmnNl94XFXOfYLJ8RBpMNidXd1rpOAVgb0vqD98xImA==" in lock_json
